services:
  kafka-standalone:
    image: 'confluentinc/cp-kafka:7.4.3'
    networks:
      - kafka-network
    ports:
      - 9092:9092
      - 9101:9101
      - 29092:29092
      - 29093:29093
    container_name: 'kafka-standalone'
    user: root
    environment:
      - CLUSTER_ID=TMzUnNsqRFGoLZPthxqXhQ
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:29093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_JMX_PORT=9101
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_NODE_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_PROCESS_ROLES=broker,controller
    restart: no
networks:
  kafka-network:
    driver: bridge